pygments: true
markdown: kramdown
## Setup
title:            Jean Bahnik
tagline:          "Another blog"
description:      "Jean Bahnik's blog."
url:              http://jeanbahnik.com
## Navigation
pages_list:
  Blog: ''
  About: '/about.html'
  Running: '/races.html'
  # Resume: '/resume'
