# Site settings
title: Jean Bahnik
email: jeanbahnik@gmail.com
baseurl: ""
url: "http://jeanbahnik.com"
twitter_username: jeanbahnik
github_username:  jeanbahnik
linkedin_username: jeanbahnik

# Build settings
markdown: kramdown
sass:
    style: :compressed
    sass_dir: _sass
